### ISSUE TITLE
Jump lists do not work on Windows 10 Preview

### ISSUE THREAD

**Issue by elyscape** [elyscape/vim-winjumplist#1]
This may be an issue with Vim never [explicitly setting an AppUserModelID](https://msdn.microsoft.com/en-us/library/windows/desktop/dd378459%28v=vs.85%29.aspx) and the shortcuts not containing one either.  The backing .automaticDestinations-ms file gets updated.  Interestingly, it seems that Vim gets two .automaticDestinations-ms files: `f01b4d95cf55d32a.automaticDestinations-ms` and `5f7b5f1e01b83767.automaticDestinations-ms`.  That may be the reason the shortcuts don't get updated, and seems like it could be caused by Vim never explicitly setting an AppUserModelID.  Further research is necessary.

**Comment by CTimmerman** [comment]
According to Process Monitor 3.10 in Windows 10 Pro, Google Chrome 45.0.2454.101 m also polls %AppData%\Roaming\Microsoft\Windows\Recent\AutomaticDestinations\5f7b5f1e01b83767.automaticDestinations-ms, 4 times per second.

**Comment by elyscape** [comment]
Without my doing anything, this appears to have resolved itself. A happy ending!
